---
title: "Video project"
output: html_document
---

1. Import the data
```{r}
data <- read.csv(file.choose())
```

2. Remove missing observations
```{r}
data <- na.omit(data)
str(data)
```

3. Summarize the numerical variables
```{r}
par(mfrow=c(2,4))
hist(data$NUMBRANCH, main="Numbranch", xlab="Numbranch")
hist(data$COSTT4_A, main="Cost", xlab="Cost")
hist(data$AVGFACSAL, main="AVGFACSAL", xlab="AVGFACSAL")
hist(data$PFTFAC, main="PFTFAC", xlab="PFTFAC")
hist(data$PCTPELL, main="PCTPELL", xlab="PCTPELL")
hist(data$UG25ABV, main="UG25ABV", xlab="UG25ABV")
hist(data$INC_PCT_LO , main="INC_PCT_LO ", xlab="PINC_PCT_LO ")
hist(data$PAR_ED_PCT_1STGEN, main="PAR_ED_PCT_1STGEN", xlab="PAR_ED_PCT_1STGEN")
hist(data$FEMALE, main="FEMALE", xlab="FEMALE")
hist(data$MD_FAMINC , main="MD_FAMINC ", xlab="MD_FAMINC ")
hist(data$PCT_WHITE, main="PCT_WHITE", xlab="PCT_WHITE")
hist(data$PCT_BLACK , main="PCT_BLACK ", xlab="PCT_BLACK")
hist(data$PCT_ASIAN , main="PCT_ASIAN ", xlab="PCT_ASIAN")
hist(data$PCT_HISPANIC , main="PCT_HISPANIC ", xlab="PCT_HISPANIC")
hist(data$PCT_BA, main="PCT_GRAD_PROF", xlab="PCT_GRAD_PROF")
hist(data$PCT_BORN_US, main="PCT_BORN_US", xlab="PCT_BORN_US")
hist(data$POVERTY_RATE, main="POVERTY_RATE", xlab="POVERTY_RATE")
hist(data$UNEMP_RATE, main="UNEMP_RATE", xlab="UNEMP_RATE")


plot(data$ADM_RATE ~ data$NUMBRANCH, main="ADM. v. Numbranch", xlab="Numbranch", ylab="ADM.")
plot(data$ADM_RATE ~ data$COSTT4_A, main="ADM. v. COSTT4_A", xlab="COSTT4_A", ylab="ADM.")
plot(data$ADM_RATE ~ data$AVGFACSAL, main="ADM. v. AVGFACSAL", xlab="AVGFACSAL", ylab="ADM.")
plot(data$ADM_RATE ~ data$PFTFAC, main="ADM. v. PFTFAC", xlab="PFTFAC", ylab="ADM.")
plot(data$ADM_RATE ~ data$PCTPELL, main="ADM. v. PCTPELL", xlab="PCTPELL", ylab="ADM.")
plot(data$ADM_RATE ~ data$UG25ABV, main="ADM. v. UG25ABV", xlab="UG25ABV", ylab="ADM.")
plot(data$ADM_RATE ~ data$INC_PCT_LO, main="ADM. v. INC_PCT_LO", xlab="INC_PCT_LO", ylab="ADM.")
plot(data$ADM_RATE ~ data$PAR_ED_PCT_1STGEN, main="ADM. v. PAR_ED_PCT_1STGEN", xlab="PAR_ED_PCT_1STGEN", ylab="ADM.")
plot(data$ADM_RATE ~ data$FEMALE, main="ADM. v. FEMALE", xlab="FEMALE", ylab="ADM.")
plot(data$ADM_RATE ~ data$MD_FAMINC, main="ADM. v. MD_FAMINC", xlab="MD_FAMINC", ylab="ADM.")
plot(data$ADM_RATE ~ data$PCT_WHITE, main="ADM. v. PCT_WHITE", xlab="PCT_WHITE", ylab="ADM.")
plot(data$ADM_RATE ~ data$PCT_BLACK, main="ADM. v. PCT_BLACK", xlab="PCT_BLACK", ylab="ADM.")
plot(data$ADM_RATE ~ data$PCT_ASIAN, main="ADM. v. PCT_ASIAN", xlab="PCT_ASIAN", ylab="ADM.")
plot(data$ADM_RATE ~ data$PCT_HISPANIC, main="ADM. v. PCT_HISPANIC", xlab="PCT_HISPANIC", ylab="ADM.")
plot(data$ADM_RATE ~ data$PCT_BA, main="ADM. v. PCT_BA", xlab="PCT_BA", ylab="ADM.")
plot(data$ADM_RATE ~ data$PCT_BORN_US, main="ADM. v. PCT_BORN_US", xlab="PCT_BORN_US", ylab="ADM.")
plot(data$ADM_RATE ~ data$POVERTY_RATE, main="ADM. v. POVERTY_RATE", xlab="POVERTY_RATE", ylab="ADM.")
plot(data$ADM_RATE ~ data$UNEMP_RATE, main="ADM. v. UNEMP_RATE", xlab="UNEMP_RATE", ylab="ADM.")

AVG <- ggplot(data = data) + geom_point(mapping = aes(x = AVGFACSAL, y = ADM_RATE))
#ggplot(data = mod_adr) + geom_point(mapping = aes(x = ADM_RATE, y = FEMALE))
print(AVG + labs(title = "Admission Rate vs. Average faculty salary",y= "Admission Rate", x = "Average faculty salary"))
FAMINC <- ggplot(data = data) + geom_point(mapping = aes(x = MD_FAMINC, y = ADM_RATE))
print(FAMINC + labs(title = "Admission Rate vs. Median family income of students",y= "Admission Rate", x = "Median family income of students"))
```
4. Summarize categorical variables
```{r}
data$CONTROL <- as.factor(data$CONTROL)
data$REGION <- as.factor(data$REGION)
data$HBCU <- as.factor(data$HBCU)
data$PBI<- as.factor(data$PBI)
data$TRIBAL <- as.factor(data$TRIBAL)
data$HSI <- as.factor(data$HSI)
data$WOMENONLY <- as.factor(data$WOMENONLY)

data$CONTROL <- factor(data$CONTROL, levels = c(1,2,3), labels = c("public", "private non-profit","private for-profit"))
data$REGION <- factor(data$REGION, levels = c(0,1,2,3,4,5,6,7,8,9), labels = c("US","New England","Mid East","Great Lakes", "Plains", "Southeast", "Southwest", "Rocky Mountains","Far West","Outlying Areas"))   
data$HBCU <- factor(data$HBCU, levels = c(0,1), labels = c("Non historically black","Historically black"))
data$PBI<- factor(data$PBI, levels = c(0,1), labels = c("Non predominatly black", "Predominantly black"))
data$TRIBAL <- factor(data$TRIBAL, levels = c(0,1), labels = c("Not tribal","Tribal"))
data$HSI <- factor(data$HSI, levels = c(0,1), labels= c("Non hispanic serving","Hispanic serving"))
data$WOMENONLY <- factor(data$WOMENONLY, levels = c(0,1), labels = c("Not womenonly","Womenonly"))

par(mfrow=c(2,4))
ControlPlot = ggplot(data, aes(x = CONTROL, y = ADM_RATE)) + geom_boxplot()
ControlPlot

RegionPlot = ggplot(data, aes(x = REGION, y = ADM_RATE)) + geom_boxplot()
RegionPlot

HBCUPlot = ggplot(data, aes(x = HBCU, y = ADM_RATE)) + geom_boxplot()
HBCUPlot

PBIPlot = ggplot(data, aes(x = PBI, y = ADM_RATE)) + geom_boxplot()
PBIPlot

TribalPlot = ggplot(data, aes(x = TRIBAL, y = ADM_RATE)) + geom_boxplot()
TribalPlot

HSIPlot = ggplot(data, aes(x = HBCU, y = ADM_RATE)) + geom_boxplot()
HSIPlot

WomenonlyPlot = ggplot(data, aes(x = WOMENONLY, y = ADM_RATE)) + geom_boxplot()
WomenonlyPlot
```

5. Selecting predictors
```{r}
fullmod <- lm(ADM_RATE ~ CONTROL+REGION+HBCU+PBI+TRIBAL+WOMENONLY+COSTT4_A+AVGFACSAL+PFTFAC+PCTPELL+UG25ABV+
            INC_PCT_LO+PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+PCT_BLACK+PCT_ASIAN+PCT_HISPANIC+
            PCT_BA+PCT_GRAD_PROF+PCT_BORN_US+POVERTY_RATE+UNEMP_RATE, data=data)
summary(fullmod)

mod1 <- lm(ADM_RATE ~ CONTROL+REGION+HBCU+PBI+TRIBAL+WOMENONLY+COSTT4_A+AVGFACSAL+PFTFAC+PCTPELL+
            INC_PCT_LO+PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+PCT_BLACK+PCT_ASIAN+PCT_HISPANIC+
            PCT_BA+PCT_GRAD_PROF+PCT_BORN_US+POVERTY_RATE+UNEMP_RATE, data=data) 
summary(mod1)

mod2 <- lm(ADM_RATE ~ CONTROL+REGION+HBCU+PBI+TRIBAL+WOMENONLY+COSTT4_A+AVGFACSAL+PFTFAC+PCTPELL+
            PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+PCT_BLACK+PCT_ASIAN+PCT_HISPANIC+
            PCT_BA+PCT_GRAD_PROF+PCT_BORN_US+POVERTY_RATE+UNEMP_RATE, data=data) 
summary(mod2)

mod3 <- lm(ADM_RATE ~ CONTROL+REGION+HBCU+PBI+TRIBAL+WOMENONLY+COSTT4_A+AVGFACSAL+PFTFAC+PCTPELL+
            PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+PCT_BLACK+PCT_ASIAN+
            PCT_BA+PCT_GRAD_PROF+PCT_BORN_US+POVERTY_RATE+UNEMP_RATE, data=data) 
summary(mod3)

mod4 <- lm(ADM_RATE ~ CONTROL+REGION+HBCU+TRIBAL+WOMENONLY+COSTT4_A+AVGFACSAL+PFTFAC+PCTPELL+
            PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+PCT_BLACK+PCT_ASIAN+
            PCT_BA+PCT_GRAD_PROF+PCT_BORN_US+POVERTY_RATE+UNEMP_RATE, data=data) 
summary(mod4)

mod5 <- lm(ADM_RATE ~ CONTROL+REGION+HBCU+TRIBAL+WOMENONLY+COSTT4_A+AVGFACSAL+PFTFAC+PCTPELL+
            PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+PCT_BLACK+
            PCT_BA+PCT_GRAD_PROF+PCT_BORN_US+POVERTY_RATE+UNEMP_RATE, data=data) 
summary(mod5)

mod6 <- lm(ADM_RATE ~ CONTROL+REGION+HBCU+TRIBAL+WOMENONLY+COSTT4_A+AVGFACSAL+PFTFAC+
            PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+PCT_BLACK+
            PCT_BA+PCT_GRAD_PROF+PCT_BORN_US+POVERTY_RATE+UNEMP_RATE, data=data) 
summary(mod6)

mod7 <- lm(ADM_RATE ~ CONTROL+REGION+HBCU+TRIBAL+WOMENONLY+COSTT4_A+AVGFACSAL+PFTFAC+
            PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+PCT_BLACK+
            PCT_BA+PCT_GRAD_PROF+POVERTY_RATE+UNEMP_RATE, data=data) 
summary(mod7)

mod8 <- lm(ADM_RATE ~ CONTROL+REGION+HBCU+TRIBAL+WOMENONLY+COSTT4_A+AVGFACSAL+PFTFAC+
            PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+PCT_BLACK+
            PCT_BA+PCT_GRAD_PROF+POVERTY_RATE, data=data) 
summary(mod8)

mod9 <- lm(ADM_RATE ~ CONTROL+HBCU+TRIBAL+WOMENONLY+COSTT4_A+AVGFACSAL+PFTFAC+
            PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+PCT_BLACK+
            PCT_BA+PCT_GRAD_PROF+POVERTY_RATE, data=data) 
summary(mod9)

mod10 <- lm(ADM_RATE ~ CONTROL+HBCU+TRIBAL+WOMENONLY+COSTT4_A+AVGFACSAL+PFTFAC+
            PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+
            PCT_BA+PCT_GRAD_PROF+POVERTY_RATE, data=data) 
summary(mod10)

mod11 <- lm(ADM_RATE ~ CONTROL+TRIBAL+WOMENONLY+COSTT4_A+AVGFACSAL+PFTFAC+
            PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+
            PCT_BA+PCT_GRAD_PROF+POVERTY_RATE, data=data) 
summary(mod11)

mod12 <- lm(ADM_RATE ~ CONTROL+TRIBAL+COSTT4_A+AVGFACSAL+PFTFAC+
            PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+
            PCT_BA+PCT_GRAD_PROF+POVERTY_RATE, data=data) 
summary(mod12)

mod2 <- lm(ADM_RATE ~ CONTROL+COSTT4_A+AVGFACSAL+PFTFAC+
            PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+
            PCT_BA+PCT_GRAD_PROF+POVERTY_RATE, data=data) 
summary(mod2)

mod13 <- lm(ADM_RATE ~ CONTROL+AVGFACSAL+PFTFAC+
            PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+
            PCT_BA+PCT_GRAD_PROF+POVERTY_RATE, data=data) 
summary(mod13)
```
6.Model diagnostic
```{r}
##Residual plots
r <- resid(mod13)

##check condition1 and condition2
pairs(~ CONTROL+AVGFACSAL+PFTFAC+
            PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+
            PCT_BA+PCT_GRAD_PROF+POVERTY_RATE, data = data)
plot(data$ADM_RATE ~ fitted(mod13), main="Y versus Y-hat", xlab="Y-hat", ylab="Y")
abline(a = 0, b = 1)
lines(lowess(data$ADM_RATE ~ fitted(mod13)), lty=2)

plot(r ~ fitted(mod13), main = "Residuals vs fittedADM_RATE", xlab = "fittedADM_RATE", ylab = "residuals")
plot(r ~ data$CONTROL, main = "Residuals vs Control", xlab = "Control", ylab = "residuals")
plot(r ~ data$AVGFACSAL, main = "Residuals vs AVGFACSAL", xlab = "AVGFACSAL", ylab = "residuals")
plot(r ~ data$PAR_ED_PCT_1STGEN, main = "Residuals vs PAR_ED_PCT_1STGEN", xlab = "PAR", ylab = "residuals")
plot(r ~ data$FEMALE, main = "Residuals vs female", xlab = "female", ylab = "residuals")
plot(r ~ data$MD_FAMINC, main = "Residuals vs MD_FAMINC", xlab = "MD_FAMINC", ylab = "residuals")
plot(r ~ data$PCT_WHITE, main = "Residuals vs PCT_WHITE", xlab = "PCT_WHITE", ylab = "residuals")
plot(r ~ data$PCT_BA, main = "Residuals vs PCT_BA", xlab = "PCT_BA", ylab = "residuals")
plot(r ~ data$PCT_GRAD_PROF, main = "Residuals vs PCT_GRAD_PROF", xlab = "PCT_GRAD_PROF", ylab = "residuals")
plot(r ~ data$POVERTY_RATE, main = "Residuals vs POVERTY_RATE", xlab = "POVERTY_RATE", ylab = "residuals")
plot(r ~ data$PFTFAC, main = "Residuals vs PFTFAC", xlab = "PFTFAC", ylab = "residuals")

qqnorm(r)
qqline(r)
```
7. check Transformation
```{r}
data$ADM_RATE <- data$ADM_RATE+0.01
data$MD_FAMINC <- data$MD_FAMINC+0.01

boxCox(mod13)

p <- powerTransform(cbind(data[,6],data[,16],data[,20],data[,21],data[,22],data[,23],data[,27],data[,28],data[,30],data[,15])~1)
summary(p)

p <- powerTransform(cbind(data[,6],data[,13],data[,16],data[,20],data[,21],data[,22],data[,23],data[,27],data[,28],data[,30],data[,15])~1)
summary(p)
```
8.Transformation
```{r}
finalmod <- lm(sqrt(ADM_RATE) ~ CONTROL+AVGFACSAL+PFTFAC+
            PAR_ED_PCT_1STGEN+FEMALE+MD_FAMINC+PCT_WHITE+
            PCT_BA+PCT_GRAD_PROF+POVERTY_RATE,data=data)
summary(finalmod)
```
9.check assumption
```{r}
r <- resid(finalmod)
plot(data$ADM_RATE ~ fitted(finalmod), main="Y versus Y-hat", xlab="Y-hat", ylab="Y")
abline(a = 0, b = 1)


plot(r ~ fitted(finalmod), main = "Residuals vs fittedADM_RATE", xlab = "fittedADM_RATE", ylab = "residuals")
plot(r ~ data$CONTROL, main = "Residuals vs Control", xlab = "Control", ylab = "residuals")
plot(r ~ data$AVGFACSAL, main = "Residuals vs AVGFACSAL", xlab = "AVGFACSAL", ylab = "residuals")
plot(r ~ data$PAR_ED_PCT_1STGEN, main = "Residuals vs PAR_ED_PCT_1STGEN", xlab = "PAR", ylab = "residuals")
plot(r ~ data$FEMALE, main = "Residuals vs female", xlab = "female", ylab = "residuals")
plot(r ~ data$MD_FAMINC, main = "Residuals vs MD_FAMINC", xlab = "MD_FAMINC", ylab = "residuals")
plot(r ~ data$PCT_WHITE, main = "Residuals vs PCT_WHITE", xlab = "PCT_WHITE", ylab = "residuals")
plot(r ~ data$PCT_BA, main = "Residuals vs PCT_BA", xlab = "PCT_BA", ylab = "residuals")
plot(r ~ data$PCT_GRAD_PROF, main = "Residuals vs PCT_GRAD_PROF", xlab = "PCT_GRAD_PROF", ylab = "residuals")
plot(r ~ data$POVERTY_RATE, main = "Residuals vs PVERTY_RATE", xlab = "POVERTY_RATE", ylab = "residuals")
plot(r ~ data$PFTFAC, main = "Residuals vs PFTFAC", xlab = "PFTFAC", ylab = "residuals")

qqnorm(r)
qqline(r)

```


